# Generated by Django 4.2.16 on 2024-09-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_discription', models.CharField(max_length=250)),
                ('designation', models.CharField(max_length=100)),
                ('designation_short_discription', models.CharField(max_length=200)),
                ('birth_date', models.DateField()),
                ('website_link', models.URLField(max_length=300)),
                ('phone', models.PositiveIntegerField()),
                ('city', models.CharField(max_length=100)),
                ('age', models.IntegerField(max_length=10)),
                ('degree', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('bottom_short_discription', models.CharField(max_length=200)),
            ],
        ),
    ]
