# Generated by Django 4.2.16 on 2024-09-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_about_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=100)),
                ('interested_title', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='about',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
