# Generated by Django 4.2.16 on 2024-09-07 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_features_alter_about_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Features',
            new_name='Feature',
        ),
    ]
