# Generated by Django 4.2.16 on 2024-09-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_features_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_discription', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=80)),
                ('t_designation', models.CharField(max_length=100)),
            ],
        ),
    ]
