# Generated by Django 4.2.16 on 2024-09-09 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_social_fb_link_remove_social_i_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='link',
            field=models.URLField(default='empty', max_length=100),
        ),
        migrations.AlterField(
            model_name='social',
            name='social_icon',
            field=models.CharField(default='empty', max_length=100),
        ),
    ]
