# Generated by Django 4.2.16 on 2024-09-09 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_social_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='social_icon',
            field=models.CharField(max_length=100),
        ),
    ]
