# Generated by Django 4.2.16 on 2024-09-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_social_social_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_icon', models.CharField(max_length=100)),
                ('s_title', models.CharField(max_length=100)),
                ('s_description', models.CharField(max_length=500)),
            ],
        ),
    ]
