# Generated by Django 4.2.16 on 2024-09-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_testimonial_image_alter_about_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(default='#', upload_to='static/assets/img/testimonials/'),
        ),
    ]
