# Generated by Django 4.2.16 on 2024-09-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_testimonial_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='icon_color',
            field=models.CharField(default='#fff', max_length=100),
        ),
    ]
