# Generated by Django 4.2.16 on 2024-09-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_feature_icon_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='s_image',
            field=models.ImageField(blank=True, null=True, upload_to='service_img/'),
        ),
    ]
